services:
  - type: web
    name: wordque-backend
    env: docker
    repo: https://github.com/mahadir04/WordQue
    rootDir: backend
    plan: starter
    region: ohio
    envVars:
      - key: GOOGLE_API_KEY
        sync: false # You will need to enter this in the Render dashboard
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: FAISS_INDEX_PATH
        value: /opt/render/project/src/data/faiss_index
    disk:
      name: wordque-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
